name: CI/CD
on:
  push:
    branches:
      - master
      - next

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/setup

      - uses: ArtiomTr/jest-coverage-report-action@v2
        id: coverage
        with:
          output: report-markdown
          test-script: yarn test

      - uses: marocchino/sticky-pull-request-comment@v2
        with:
          message: ${{ steps.coverage.outputs.report }}

  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/setup

      - name: ESLint
        run: yarn lint:eslint

      - name: Prettier
        run: yarn lint:prettier

      - name: Types
        run: yarn tsc

  build:
    name: Build
    runs-on: ubuntu-latest
    needs: [test, lint]
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/setup

      - name: Build
        run: yarn build

      - uses: codfish/semantic-release-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

  # demo:
  #   needs: build
  #   name: Demo
  #   runs-on: ubuntu-latest
  #   defaults:
  #     run:
  #       working-directory: demo
  #   steps:
  #     - name: Checkout
  #       uses: actions/checkout@v1

  #     - name: Setup Node.js
  #       uses: actions/setup-node@v1
  #       with:
  #         node-version: 12

  #     - run: npm ci

  #     - name: Build
  #       run: npm run build

  #     - name: Deploy
  #       uses: peaceiris/actions-gh-pages@v3
  #       with:
  #         github_token: ${{ secrets.GITHUB_TOKEN }}
  #         publish_dir: ./demo/dist
